// get list CATEGORY 
export const SET_LIST_CATEGORY = 'SET_LIST_CATEGORY';
export const SET_COMENT = 'SET_COMENT'
export const SET_LIST_PRODUCTS = "SET_LIST_PRODUCTS";
export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const SET_DETAIL_PRODUCT = "SET_DETAIL_PRODUCT"
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
